apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  selector:
    app: hello-python
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
spec:
  selector:
    matchLabels:
      app: hello-python
  replicas: 4
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: hello-python:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000


# To build the image, run the following command in the terminal:
# docker build -t hello-python:latest .
# To apply the deployment and service, run the following command in the terminal:
# kubectl apply -f pod.yaml
# To check the status of the deployment and service, run the following command in the terminal:
# kubectl get deployments
# kubectl get services
